ingress:
  enabled: true
  className: nginx
  hosts:
    - host: gitea.local
      paths:
        - path: /
          pathType: Prefix

gitea:
  admin:
    existingSecret: gitea-admin
  config:
    webhook:
      ALLOWED_HOST_LIST: "el-gitea-listener.cicd.svc.cluster.local,el-gitea-listener.cicd,*.cicd.svc.cluster.local,*.svc.cluster.local"


service:
  http:
    type: ClusterIP
