apiVersion: v1
kind: ServiceAccount
metadata:
  name: el-sa
  namespace: cicd

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tekton-triggers-eventlistener-cluster-access
rules:
  - apiGroups: ["triggers.tekton.dev"]
    resources:
      - clusterinterceptors
      - clustertriggerbindings
    verbs: ["get", "list", "watch"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: el-role
  namespace: cicd
rules:
  - apiGroups: ["tekton.dev"]
    resources: ["pipelineruns"]
    verbs: ["create"]
  - apiGroups: ["triggers.tekton.dev"]
    resources:

      - eventlisteners
      - interceptors
      - triggers
      - triggerbindings
      - triggertemplates
    verbs: ["get", "list", "watch"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tekton-triggers-eventlistener-cluster-access-binding
subjects:
  - kind: ServiceAccount
    name: el-sa
    namespace: cicd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tekton-triggers-eventlistener-cluster-access

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: el-rb
  namespace: cicd
subjects:
  - kind: ServiceAccount
    name: el-sa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: el-role
