apiVersion: v1
kind: ServiceAccount
metadata:
  name: el-sa
  namespace: cicd
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: el-role
  namespace: cicd
rules:
  - apiGroups: ["tekton.dev"]
    resources: ["pipelineruns"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: el-rb
  namespace: cicd
subjects:
  - kind: ServiceAccount
    name: el-sa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: el-role
