image:
  repository: localhost:5000/todos-spa
  tag: "latest"
  pullPolicy: Always

replicaCount: 1

service:
  port: 8081

ingress:
  enabled: true
  className: nginx
  host: "todos-spa.local"
  path: /

env:
  nodeEnv: "production"
  apiHost: "todos-api.local"

resources: {}
