apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-web
  namespace: workshop-03
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpd-web
  template:
    metadata:
      labels:
        app: httpd-web
    spec:
      containers:
        - name: web
          image: registry.access.redhat.com/ubi10/httpd-24
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: httpd-content
              mountPath: /usr/local/apache2/htdocs/index.html # zámerná chyba, zmeň na /var/www/html/index.html
              subPath: index.html
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "100m"
              memory: "128Mi"
      volumes:
        - name: httpd-content
          configMap:
            name: httpd-content
