apiVersion: apps/v1
kind: Deployment
metadata:
  name: crash-app
  namespace: workshop-02
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crash-app
  template:
    metadata:
      labels:
        app: crash-app
    spec:
      containers:
        - name: app
          image: busybox:1.36
          command:
            - sh
            - -c
            - "echo 'Starting app'; sleep 5; exit 1" # replace command to prevent crash
            # - "echo 'Starting app'; sleep 3600"
