apiVersion: apps/v1
kind: Deployment
metadata:
  name: probe-app
  namespace: workshop-02
spec:
  replicas: 1
  selector:
    matchLabels:
      app: probe-app
  template:
    metadata:
      labels:
        app: probe-app
    spec:
      containers:
        - name: web
          image: docker.io/euthymos/vue-nginx-demo:0.2
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /healthz # change to '/'
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10