apiVersion: v1
kind: Service
metadata:
  name: demo-app
  namespace: workshop-02
spec:
  type: NodePort
  selector:
    app: demo-app
  ports:
    - port: 8080        # port slu≈æby
      targetPort: 8080  # port v kontajneri
      protocol: TCP