apiVersion: v1
kind: Service
metadata:
  name: {{ include "todo-spa.fullname" . }}
spec:
  selector:
    app: {{ include "todo-spa.name" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
