apiVersion: v2
name: todos-api
description: Todo API service (Node/Express) with MongoDB dependency
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: mongodb
    version: 15.6.0
    repository: https://charts.bitnami.com/bitnami
