replicaCount: 1

env:
  nodeEnv: "development"
  apiHost: "todo-dev.local"

ingress:
  enabled: true
  host: todo-spa-dev.local

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 256Mi
