replicaCount: 3

env:
  nodeEnv: "production"
  apiHost: "todo.local"

ingress:
  enabled: true
  host: todo-spa.local

resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
